#!/usr/bin/env bash

## Run Code Sniffer (phpcbf) against given path
##
## Usage: fin phpcbf <path>
##
## Uses Drupal standards.
##
## Includes extensions: php, module, inc, install, test, profile, theme
## Ignores:   *.pages*.inc

#-------------------------- Helper functions --------------------------------

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../functions.sh"

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Sanity Check --------------------------------

if [[ "$1" == "" ]]; then
  echo "Usage: fin phpcbf <path>"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

subheader "Running PHP Code Beautifier..."

fin run phpcbf \
  --standard=Drupal -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.pages*.inc" \
  "$1"

#-------------------------- END: Execution --------------------------------
