#!/usr/bin/env php
<?php
## Wrapper for running front-end development tools
##
## Usage: fin swig gulp-watch
#: exec_target = cli

if (empty($argv[1])) {
  unset($_SERVER['argv'][1]);
  unset($argv[1]);
}

$loader = require_once '/var/www/' . $_ENV['DOCROOT'] . '/autoload.php';

$loader->addPsr4('VML\\', __DIR__ . '/src/VML', true);

use VML\Util\SingleCommandApplication;
use VML\Swig;

$application = new SingleCommandApplication(new Swig());
$application->run();
