#!/bin/bash
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"

# Run the prepush script in the frontend package.json
command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=~/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && nvm use
}

RED='\033[0;31m';
GREEN='\033[0;32m';
ORANGE='\033[0;33m';
VUE_PROJECT="docroot/themes/custom/mytheme/vue"
cd $VUE_PROJECT

# Check if prepush script is defined, skip if not
has_hook_script prepush || exit 0

# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
export PATH="$PATH:/usr/local/bin:/usr/local"

# nvm path with standard installation
load_nvm ~/.nvm

# nvm path installed with Brew
load_nvm /usr/local/opt/nvm

# Check that npm exists
command_exists npm || {
  echo >&2 "\n${RED}can't find npm in PATH, skipping prepush script in ${VUE_PROJECT}/package.json"
  exit 0
}

# Export Git hook params
export GIT_PARAMS="$*"

# Run npm script
echo -e "Running frontend prepush hook (node `node -v`)"
echo

npm run -s prepush || {
  echo
  echo "pre-push hook failed"
  exit 1
}

exit $?
